language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
install:
  - composer require phpunit/phpunit:5.7.14
before_script: find / -name phpunit*
script: phpunit --bootstrap test/bootstrap.php test/